outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/04_07_map
sampleFile: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/nguyenb/tnseq/scratch/maps/samples.txt
dataDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/chris/hardt/nguyenb/tnseq_mapping_2031/data
metaDir:
controlFile:
multiplex_codes:
genome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/ref/Salmonella_genome_FQ312003.1_SL1344.fasta
gff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/ref/Salmonella_genome+plasmids.gff
fwd: _1.fq.gz
rvr: _2.fq.gz


tn: GTGTATAAGAGACAG:17:13:before