outDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/mapping/tmp
sampleFile: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/mapping/samples.txt
dataDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/mapping
Bdb: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/ref/Salmonella_genome_FQ312003.1_SL1344.fasta
gff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/tnseq/ref/Salmonella_genome+plasmids.gff
fwd: _1.fq
rvr: _2.fq


tn: GTGTATAAGAGACAG:17:13:before